export const PAGE_NAME_DICT = {
  INIT_PAGE: "INIT_PAGE",
  ABOUT_PAGE: "ABOUT_PAGE",
  EXPLIST_PAGE: "EXPLIST_PAGE",
  PROJECT_PAGE: "PROJECT_PAGE",
  NEWPROJECT_PAGE: "NEWPROJECT_PAGE",
  MODIFY_PAGE: "MODIFY_PAGE",
  EXP_PAGE: "EXP_PAGE",
  REGISTER_PAGE: "REGISTER_PAGE",
  LOGIN_PAGE: "LOGIN_PAGE",
};

export const PAGE_NAME_DICT_CN = {
  INIT_PAGE: "初始页面",
  ABOUT_PAGE: "关于项目",
  EXPLIST_PAGE: "实验列表",
  PROJECT_PAGE: "项目内容",
  NEWPROJECT_PAGE: "新建项目",
  MODIFY_PAGE: "修改项目",
  EXP_PAGE: "实验内容",
  REGISTER_PAGE: "新用户注册",
  LOGIN_PAGE: "用户登录",
};
