export const PAGE_NAME_DICT = {
  INIT_PAGE: "INIT_PAGE",
  ABOUT_PAGE: "ABOUT_PAGE",
  EXPLIST_PAGE: "EXPLIST_PAGE",
  PROJECT_PAGE: "PROJECT_PAGE",
  NEWPROJECT_PAGE: "NEWPROJECT_PAGE",
};

export const PAGE_NAME_DICT_CN = {
  INIT_PAGE: "初始页面",
  ABOUT_PAGE: "关于项目",
  EXPLIST_PAGE: "实验列表",
  PROJECT_PAGE: "项目内容",
  NEWPROJECT_PAGE: "新建实验",
};
