export const PAGE_NAME_DICT = {
  INIT_PAGE: "INIT_PAGE",
  ERROR_PAGE: "ERROR_PAGE",
  ABOUT_PAGE: "ABOUT_PAGE",
  PROJLIST_PAGE: "PROJLIST_PAGE",
  TRASH_PAGE: "TRASH_PAGE",
  PROJECT_PAGE: "PROJECT_PAGE",
  NEWPROJECT_PAGE: "NEWPROJECT_PAGE",
  MODIFY_PAGE: "MODIFY_PAGE",
  EXP_PAGE: "EXP_PAGE",
  REGISTER_PAGE: "REGISTER_PAGE",
  LOGIN_PAGE: "LOGIN_PAGE",
  PROFILE_PAGE: "PROFILE_PAGE",
};

export const PAGE_NAME_DICT_CN = {
  INIT_PAGE: "初始页面",
  ERROR_PAGE: "Oops...",
  ABOUT_PAGE: "关于项目",
  PROJLIST_PAGE: "项目列表",
  TRASH_PAGE: "回收站",
  PROJECT_PAGE: "项目内容",
  NEWPROJECT_PAGE: "新建项目",
  MODIFY_PAGE: "修改项目",
  EXP_PAGE: "实验内容",
  REGISTER_PAGE: "新用户注册",
  LOGIN_PAGE: "用户登录",
  PROFILE_PAGE: "个人信息",
};
